name: BRInE
channels:
- conda-forge
- defaults
dependencies:
- altair=1.2.1=py_0
- appnope=0.1.0=py36_0
- bleach=2.0.0=py36_0
- branca=0.2.0=py_1
- bzip2=1.0.6=1
- click=6.7=py36_0
- click-plugins=1.0.3=py36_0
- cligj=0.4.0=py36_0
- curl=7.55.1=0
- cycler=0.10.0=py36_0
- descartes=1.1.0=py36_0
- entrypoints=0.2.3=py36_1
- expat=2.2.5=0
- folium=0.5.0=py_0
- fontconfig=2.12.6=0
- freetype=2.8.1=0
- freexl=1.0.4=0
- geopandas=0.3.0=py36_0
- geopy=1.11.0=py36_0
- geos=3.6.2=1
- gettext=0.19.8.1=0
- giflib=5.1.4=0
- hdf4=4.2.13=0
- hdf5=1.10.1=1
- html5lib=0.999999999=py36_0
- icu=58.2=0
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.9.6=py36_0
- jpeg=9b=2
- json-c=0.12.1=0
- jupyter_client=5.1.0=py36_0
- kealib=1.4.7=4
- krb5=1.14.2=0
- libdap4=3.19.2=1
- libiconv=1.15=0
- libnetcdf=4.4.1.1=10
- libpng=1.6.34=0
- libsodium=1.0.15=1
- libspatialindex=1.8.5=1
- libssh2=1.8.0=2
- libtiff=4.0.9=0
- libxml2=2.9.5=2
- markupsafe=1.0=py36_0
- mistune=0.8=py36_0
- munch=2.2.0=py36_0
- nbconvert=5.3.1=py_1
- networkx=2.0=py36_0
- notebook=5.2.1=py36_2
- osmnx=0.6=py36_1
- pandas=0.21.0=py36_0
- pandoc=2.0.0.1=1
- pandocfilters=1.4.1=py36_0
- pcre=8.39=0
- pexpect=4.3.0=py36_0
- pickleshare=0.7.4=py36_0
- pixman=0.34.0=1
- poppler-data=0.4.8=0
- proj4=4.9.3=5
- prompt_toolkit=1.0.15=py36_0
- psycopg2=2.7.3.2=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyproj=1.9.5.1=py36_0
- pysal=1.14.3=py36_0
- python-dateutil=2.6.1=py36_0
- pyzmq=16.0.2=py36_2
- rtree=0.8.3=py36_0
- shapely=1.6.2=py36_1
- simplegeneric=0.8.1=py36_0
- sqlalchemy=1.1.13=py36_0
- terminado=0.8=py36_0
- testpath=0.3.1=py36_0
- tornado=4.5.2=py36_0
- vega=0.4.4=py36_1
- vincent=0.4.4=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- xerces-c=3.2.0=0
- zeromq=4.2.1=1
- asn1crypto=0.22.0=py36hb705621_1
- ca-certificates=2017.08.26=ha1e5d58_0
- cairo=1.14.10=h913ea44_6
- certifi=2017.11.5=py36ha569be9_0
- cffi=1.10.0=py36h880867e_1
- chardet=3.0.4=py36h96c241c_1
- cryptography=2.0.3=py36h22d4226_1
- decorator=4.1.2=py36h69a1b52_0
- fiona=1.7.10=py36h6a33aa8_0
- glib=2.53.6=h33f6a65_2
- idna=2.6=py36h8628d0a_1
- intel-openmp=2018.0.0=h8158457_8
- ipython_genutils=0.2.0=py36h241746c_0
- jsonschema=2.6.0=py36hb385e00_0
- jupyter_core=4.4.0=py36h79cf704_0
- libboost=1.65.1=h8182a68_3
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- libgdal=2.2.2=ha430587_1
- libgfortran=3.0.1=h93005f0_2
- libkml=1.3.0=hc0cae1e_3
- libpq=9.6.6=h0190f75_0
- libspatialite=4.3.0a=h0a2fa02_18
- matplotlib=2.1.0=py36h5068139_0
- mkl=2018.0.1=hfbd8650_4
- nbformat=4.4.0=py36h827af21_0
- ncurses=6.0=hd04f020_2
- numpy=1.13.3=py36h2cdce51_0
- openjpeg=2.2.0=h60bf5c3_2
- openssl=1.0.2m=h86d3e6a_1
- pip=9.0.1=py36h1555ced_4
- plotly=2.1.0=py36h9570409_0
- poppler=0.60.1=hb654a48_0
- pycparser=2.18=py36h724b2fc_1
- pyopenssl=17.2.0=py36h5d7bf08_0
- pysocks=1.6.7=py36hfa33cec_1
- python=3.6.3=h5ce8c04_4
- pytz=2017.3=py36hf0bf824_0
- readline=7.0=hc1231fa_4
- requests=2.18.4=py36h4516966_1
- scikit-learn=0.19.1=py36hffbff8c_0
- scipy=1.0.0=py36h1de22e9_0
- setuptools=36.5.0=py36h2134326_0
- six=1.11.0=py36h0e22d5e_1
- sqlite=3.20.1=h7e4c145_2
- tk=8.6.7=h35a86e2_3
- traitlets=4.3.2=py36h65bd3ce_0
- urllib3=1.22=py36h68b9469_0
- wheel=0.30.0=py36h5eb2c71_1
- xz=5.2.3=h0278029_2
- zlib=1.2.11=hf3cbc9b_2
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
prefix: /Users/sanchez.hmsc/miniconda2/envs/BRInE

